alter table JCRM_T_CONTACT_PHONE add constraint FK_JCRM_T_CONTACT_PHONE_ON_CONTACT_TYPE foreign key (CONTACT_TYPE_ID) references JCRM_D_CONTACTS_TYPE(ID);
alter table JCRM_T_CONTACT_PHONE add constraint FK_JCRM_T_CONTACT_PHONE_ON_CONTACT_KIND foreign key (CONTACT_KIND_ID) references JCRM_D_CONTACT_KIND(ID);
alter table JCRM_T_CONTACT_PHONE add constraint FK_JCRM_T_CONTACT_PHONE_ON_IDENTITY foreign key (IDENTITY_ID) references ARCLAB_IDENTITY(ID);
create index IDX_JCRM_T_CONTACT_PHONE_ON_CONTACT_TYPE on JCRM_T_CONTACT_PHONE (CONTACT_TYPE_ID);
create index IDX_JCRM_T_CONTACT_PHONE_ON_CONTACT_KIND on JCRM_T_CONTACT_PHONE (CONTACT_KIND_ID);
create index IDX_JCRM_T_CONTACT_PHONE_ON_IDENTITY on JCRM_T_CONTACT_PHONE (IDENTITY_ID);
