alter table ARCLAB_IDENTITY_APPLICATION add constraint FK_ARCLAB_IDENTITY_APPLICATION_ON_IDENTITY foreign key (IDENTITY_ID) references ARCLAB_IDENTITY(ID);
alter table ARCLAB_IDENTITY_APPLICATION add constraint FK_ARCLAB_IDENTITY_APPLICATION_ON_ID foreign key (ID) references JCRM_APPLICATION(ID) on delete CASCADE;
create index IDX_ARCLAB_IDENTITY_APPLICATION_ON_IDENTITY on ARCLAB_IDENTITY_APPLICATION (IDENTITY_ID);
