alter table ARCLAB_EDS_REGISTRY add constraint FK_ARCLAB_EDS_REGISTRY_ON_FILE_TO_SIGN foreign key (FILE_TO_SIGN_ID) references SYS_FILE(ID);
alter table ARCLAB_EDS_REGISTRY add constraint FK_ARCLAB_EDS_REGISTRY_ON_CURRENT_USER foreign key (CURRENT_USER_ID) references SEC_USER(ID);
create index IDX_ARCLAB_EDS_REGISTRY_ON_FILE_TO_SIGN on ARCLAB_EDS_REGISTRY (FILE_TO_SIGN_ID);
create index IDX_ARCLAB_EDS_REGISTRY_ON_CURRENT_USER on ARCLAB_EDS_REGISTRY (CURRENT_USER_ID);
