alter table JCRM_DOC_FORMED add constraint FK_JCRM_DOC_FORMED_ON_APPLICATION foreign key (APPLICATION_ID) references JCRM_APPLICATION(ID);
alter table JCRM_DOC_FORMED add constraint FK_JCRM_DOC_FORMED_ON_DOC_FILE foreign key (DOC_FILE_ID) references SYS_FILE(ID);
create unique index IDX_JCRM_DOC_FORMED_UK_DOC_FILE_ID on JCRM_DOC_FORMED (DOC_FILE_ID) where DELETE_TS is null ;
create index IDX_JCRM_DOC_FORMED_ON_APPLICATION on JCRM_DOC_FORMED (APPLICATION_ID);
create index IDX_JCRM_DOC_FORMED_ON_DOC_FILE on JCRM_DOC_FORMED (DOC_FILE_ID);
